Update dotnet-desktop.yml

diff --git a/.github/workflows/dotnet-desktop.yml b/.github/workflows/dotnet-desktop.yml
--- a/.github/workflows/dotnet-desktop.yml
+++ b/.github/workflows/dotnet-desktop.yml
@@ -81,18 +81,23 @@ jobs:
     #- name: Execute unit tests
      # run: dotnet test
 
-    - name: Test
-      run: dotnet test --logger "trx;LogFileName=test-results.trx" || true
+    #- name: Test
+ #     run: dotnet test --logger "trx;LogFileName=test-results.trx" || true
 
-    - name: Test Report
-      uses: dorny/test-reporter@v1
-      if: always()
-      with:
-        name: DotNET Tests
-        path: "**/test-results.trx"                            
-        reporter: dotnet-trx
-        fail-on-error: true
-
+   # - name: Test Report
+    #  uses: dorny/test-reporter@v1
+     # if: always()
+      #with:
+       # name: DotNET Tests
+        #path: "**/test-results.trx"                            
+        #reporter: dotnet-trx
+        #fail-on-error: true
+        
+    - name: Install NUnit.ConsoleRunner
+      run: nuget install NUnit.ConsoleRunner -Version 3.13.0 -DirectDownload -OutputDirectory
+        
+    - name: Run UnitTests
+      run: ./NUnit.ConsoleRunner.3.13.0/tools/nunit3-console.exe  path/to/test.dll
 
     - name: Setup NuGet.exe for use with actions
       uses: NuGet/setup-nuget@v2.0.0
